export const SEED_CLIENTS = [
  {
    name: "Evelyn Hart",
    phone: "+1 (416) 555-0101",
    tags: ["SENIOR", "MEDICAL", "HOUSING"],
    risk_level: "MED",
    notes: [
      "Worker conducted initial home visit at client's apartment on [Date], arriving at 10:00 AM.\n- Worker knocked on the door multiple times over a 5-minute period before the client answered.\n- Client stated, 'I didn't invite anyone over, go away,' through the closed door.\n- Worker identified self and explained the purpose of the visit (wellness check following landlord complaint).\n- Client partially opened the door and stated reluctance to allow entry.\n- Worker observed a strong foul odor emanating from the apartment.\n- Worker observed significant garbage accumulation in the hallway visible from the door, including multiple full garbage bags and stacked newspapers reaching approximately 3 feet high.\n- Client observed to be wearing stained clothing that appeared unwashed.\n- Client asked the worker, 'What year is it?' and appeared confused and disoriented regarding the current date and time.\n- Worker requested to step inside to discuss further; client agreed after 10 minutes of conversation at the threshold.\n- Inside the apartment, worker observed the kitchen sink overflowing with unwashed dishes and visible fruit flies.\n- Worker observed the refrigerator contained spoiled food items and no fresh produce or dairy.\n- Client stated she had not eaten breakfast and was 'waiting for her husband,' who is documented as deceased five years ago.\n- Worker contacted emergency medical services (EMS) for a wellness assessment due to observed cognitive decline and unsafe living conditions.\n- Worker remained with the client until EMS arrived at 10:45 AM.\n- EMS assessed client and transported her to General Hospital for evaluation.\n- Worker secured the apartment and locked the door at 11:00 AM.\n\n[RISK:HIGH]",
      "Worker conducted follow-up visit with public health nurse at General Hospital on [Date], beginning at 2:00 PM.\n- Worker and nurse met with the client in her hospital room.\n- Client was sitting up in bed and appeared more alert than during the previous home visit.\n- Nurse conducted a preliminary cognitive assessment; client accurately stated the year and her location.\n- Client agreed to a full medical assessment by the geriatric physician on staff.\n- Worker discussed nutritional needs with the client; client stated she often forgets to cook.\n- Worker initiated a Meals on Wheels application and completed the dietary preferences section with the client.\n- Client stated she has no local family and her only living relative is a nephew in British Columbia whom she has not spoken to in 'many years.'\n- Worker obtained client's consent to attempt to contact the nephew.\n- Worker contacted the hospital social worker to coordinate discharge planning and provided a summary of the home conditions.\n- Worker observed physical therapy session where client demonstrated mobility with a walker but reported pain level as '6 out of 10.'\n- Worker scheduled a secondary visit for the day of discharge.\n\n[RISK:MED]",
      "Worker coordinated discharge planning with hospital social worker via phone conference on [Date] at 9:30 AM.\n- Hospital social worker reported client suffered a fractured hip following a fall in her apartment, which occurred after the previous visit.\n- Medical team stated client requires surgery and a minimum 3-week stay in a rehabilitation facility.\n- Worker provided an update on the condition of the client's apartment, noting it is currently unsafe for discharge due to hoarding and lack of sanitation.\n- Worker requested an extension on the Meals on Wheels application start date pending the client's discharge from rehab.\n- Worker contacted the landlord to request a delay on any property standards actions due to the client's hospitalization; landlord verbally agreed to a 30-day hold.\n- Worker initiated an application for specialized heavy-duty cleaning services through municipal funding.\n\n[RISK:HIGH]",
      "Worker attended in-person discharge planning meeting at the rehabilitation center on [Date] at 1:00 PM.\n- Attendees included the worker, client, physical therapist, and rehabilitation center social worker.\n- Client to be transferred to the facility's transitional care unit on Friday.\n- Physical therapist stated the current apartment layout, particularly the narrow hallway and cluttered floor, is unsuitable for a walker.\n- Worker presented photographs of the apartment to the care team to illustrate housing challenges.\n- Client stated distress over the idea of her belongings being moved or thrown away.\n- Worker explained the necessity of a clear path for safety and fire code compliance.\n- Worker committed to researching assisted living options that offer higher levels of daily support.\n- Worker spent an additional 30 minutes with the client discussing her fears regarding losing independence.\n- Client verbally agreed to allow the heavy-duty cleaning service to enter the apartment next week to establish a safe 3-foot pathway.\n\n[RISK:MED]",
      "Worker visited client at rehabilitation center on [Date] at 10:15 AM.\n- Client was observed participating in an occupational therapy session, practicing transferring from a chair to a standing position.\n- Client stated significant anxiety regarding her eventual return to her apartment.\n- Client stated, 'I don't think I can manage the stairs anymore.'\n- Worker discussed subsidized seniors housing options and the process for applying for a primary ground-floor unit.\n- Worker assisted the client in completing the initial intake forms for the municipal centralized housing registry.\n- Client provided her signature on the consent forms for the worker to act as an authorized representative.\n- Worker confirmed the heavy-duty cleaning service completed the pathway clearance the previous day.\n- Worker showed the client photographs of the cleared pathway; client expressed relief but reiterated her desire to relocate.\n- Worker scheduled a follow-up appointment with the client's assigned occupational therapist to review home modification needs if relocation is delayed.\n\n[RISK:LOW]"
    ]
  },
  {
    name: "Jamal Oates",
    phone: "+1 (416) 555-0212",
    tags: ["YOUTH", "LEGAL", "SUBSTANCE_USE"],
    risk_level: "HIGH",
    notes: [
      "Worker conducted intake interview at youth detention center on [Date] at 10:00 AM.\n- Client is a 17-year-old minor currently awaiting trial for theft under $5000 and possession of stolen property.\n- Worker observed client pacing the interview room and exhibiting signs of agitation, including rapid speech and avoiding eye contact.\n- Client stated he had been using methamphetamines daily for the past three weeks prior to his arrest.\n- Client stated he was stealing to support his substance use.\n- Client stated he has been disconnected from his legal guardian (maternal aunt) for approximately 2 months following a physical altercation.\n- Worker contacted the aunt via phone during the intake; aunt stated she is unwilling to have the client return to her residence at this time due to safety concerns.\n- Worker reviewed the client's previous child welfare involvement; records indicate three previous placements in group homes.\n- Client requested assistance with obtaining bail.\n- Worker contacted the assigned Legal Aid duty counsel to discuss release planning options.\n- Worker drafted a tentative release plan proposing a bed at the local youth shelter and mandatory daily check-ins.\n\n[RISK:HIGH]",
      "Worker attended court appearance alongside client at youth justice court on [Date] at 9:00 AM.\n- Worker presented the proposed release plan to the judge and duty counsel.\n- Charges were conditionally withdrawn pending the client's successful completion of a 6-month diversion program.\n- Conditions of the diversion program require the client to abstain from illicit substances, complete 40 hours of community service, and reside at the approved youth shelter.\n- Client verbally agreed to the conditions in front of the judge.\n- Worker escorted the client from the courthouse to the youth shelter to complete the intake process.\n- Worker and client met with the shelter intake coordinator to review house rules and curfew.\n- Client verbally agreed to attend regular weekly check-ins with the worker and bi-weekly substance use counseling sessions at the community health center.\n- Worker provided the client with a monthly transit pass and a $25 grocery gift card.\n\n[RISK:MED]",
      "Worker conducted scheduled check-in with client at community center on [Date]. Meeting scheduled for 2:00 PM; client arrived at 2:30 PM.\n- Client arrived smelling of cannabis; worker noted bloodshot eyes.\n- Client stated he got lost on the transit system, causing the delay.\n- Worker reviewed the diversion program conditions regarding substance use; client stated he 'only smoked a joint to calm down.'\n- Worker documented the substance use discussion and reminded the client of the potential legal consequences of a program breach.\n- Client stated interest in completing his GED, mentioning he dropped out in grade 10.\n- Worker conducted a career interest inventory exercise with the client for 20 minutes.\n- Worker provided the client with the contact information and enrollment dates for a local adult learning center that offers alternative education programs for youth.\n- Worker assisted the client in drafting an email to the learning center's intake coordinator requesting an appointment.\n- Client stated he feels overwhelmed by the shelter rules but has not had any conflicts with staff or other residents.\n\n[RISK:LOW]",
      "Worker attempted to contact client for scheduled appointment at the local library on [Date] at 3:00 PM.\n- Client did not attend the appointment.\n- Worker waited at the location until 3:30 PM.\n- Worker telephoned the client at 3:15 PM and 3:30 PM; both calls proceeded directly to voicemail.\n- Worker contacted the youth shelter at 3:45 PM; shelter staff reported the client missed curfew the previous night and his bed was given away.\n- Worker contacted the local street outreach team via email to flag the client as missing from his approved residence.\n- Worker contacted the client's substance use counselor; counselor stated the client had missed his last two appointments.\n- Worker contacted a known associate of the client (another youth from the shelter) who stated he had not seen the client in 3 days.\n- Worker documented the missed appointment and residential absence as a potential breach of the diversion program conditions.\n- Worker filed a missing youth report with the local police division at 4:30 PM as required by agency protocol.\n\n[RISK:HIGH]",
      "Worker met with client at a coffee shop following street outreach team contact on [Date] at 11:00 AM.\n- Outreach team located the client in an encampment earlier that morning and facilitated contact.\n- Client appeared disheveled, reporting he had not slept in two days.\n- Client stated he experienced a substance relapse involving crystal meth and had been staying with an older acquaintance in the encampment.\n- Client stated a desire to 'get back on track' and expressed fear of returning to detention.\n- Worker contacted the youth shelter supervisor to negotiate a temporary emergency bed; supervisor agreed to a one-night placement pending a review meeting.\n- Worker accompanied the client to a walk-in clinic to address a minor infection on his arm.\n- Worker reconnected client with substance use counselor via phone; scheduled a joint meeting for the following Tuesday.\n- Worker notified the diversion program officer of the client's whereabouts and current status.\n- Worker and client updated the safety and crisis plan, identifying new triggers that led to the relapse.\n\n[RISK:MED]"
    ]
  },
  {
    name: "Clara & Mateo Silva",
    phone: "+1 (416) 555-0323",
    tags: ["FAMILY_SUPPORT", "EMPLOYMENT", "IMMIGRATION"],
    risk_level: "LOW",
    notes: [
      "Worker conducted initial meeting with Silva family at their residence on [Date] at 5:00 PM.\n- Clients are recent immigrants from Colombia who arrived in Canada six months ago.\n- Meeting included husband (Mateo), wife (Clara), and two children (ages 6 and 8).\n- Client Mateo stated extreme difficulty finding employment in his field of civil engineering; he reported submitting over 50 applications with no interviews.\n- Client Clara stated she works part-time (20 hours/week) at a local grocery store as a cashier.\n- Clients stated they are struggling to afford the $2200/month rent for their 2-bedroom apartment.\n- Worker reviewed the family's financial documents; current monthly income is approximately $1800, creating a monthly deficit.\n- Clients stated they have been relying on modest savings, which are nearly depleted.\n- Worker observed the apartment is sparsely furnished but clean and safe for the children.\n- Worker provided the family with addresses for two local food banks and a clothing depot.\n- Worker scheduled separate follow-up appointments with Mateo regarding employment and with Clara regarding family benefits.\n\n[RISK:MED]",
      "Worker met with client Mateo at the employment services center on [Date] at 10:00 AM.\n- Worker spent 45 minutes reviewing Mateo's resume, noting it was formatted according to Colombian standards, not Canadian norms.\n- Worker assisted the client in reformatting the resume into a chronological Canadian style, highlighting specific engineering software proficiencies.\n- Worker assisted the client with registering for a credential evaluation service (WES) to have his foreign engineering degree officially recognized in Canada.\n- Client stated he feels demoralized and is considering applying for minimum wage warehouse jobs to support his family.\n- Worker validated the client's financial anxiety but encouraged him to pursue specialized immigrant professional programs first.\n- Worker referred the client to an employment agency that specializes in placing immigrant professionals in technical fields.\n- Worker and client practiced a 5-minute 'elevator pitch' for networking events.\n\n[RISK:LOW]",
      "Worker met with client Clara at the community center on [Date] at 1:00 PM.\n- Worker assisted the client in completing the application for the Canada Child Benefit (CCB), which the family had not yet applied for.\n- Worker reviewed the required documentation (passports, rental agreement, temporary resident visas) and submitted the forms online on the client's behalf.\n- Client stated the extra income from the CCB will significantly ease the family's financial burden and ensure they can afford winter clothing for the children.\n- Worker provided information regarding subsidized after-school programs for the children, allowing Clara to potentially take on additional work hours.\n- Client stated she is interested in taking ESL (English as a Second Language) classes to improve her customer service skills.\n- Worker registered the client for an evening ESL class at the local library.\n\n[RISK:LOW]",
      "Worker conducted interview preparation with client Mateo at the community center on [Date] at 3:00 PM.\n- Client stated he secured an interview for a junior drafting position at a mid-sized construction firm, scheduled for next Tuesday.\n- Client brought a printed copy of the job description; worker and client reviewed the requirements.\n- Worker and client conducted a 45-minute mock interview, practicing behavioral questions (e.g., 'Tell me about a time you handled a conflict on a project').\n- Worker provided feedback on the client's responses, focusing on the STAR method (Situation, Task, Action, Result).\n- Worker and client discussed Canadian workplace norms, including expectations around communication styles and punctuality.\n- Client stated he felt much more confident after the practice session.\n- Worker provided the client with a professional portfolio folder to organize his drafting samples.\n\n[RISK:LOW]"
    ]
  },
  {
    name: "Leo Vance",
    phone: "+1 (416) 555-0434",
    tags: ["MENTAL_HEALTH", "SUBSTANCE_USE", "HOUSING"],
    risk_level: "HIGH",
    notes: [
      "Worker conducted emergency crisis intervention on [Date] at 11:30 PM in a downtown municipal parking garage.\n- Security guard contacted the agency reporting an individual trespassing and causing a disturbance on level P3.\n- Worker arrived and observed the client pacing rapidly, waving his arms, and shouting at empty spaces.\n- Worker approached slowly, identifying self; client exhibited severe auditory hallucinations, stating that 'the radio signals are burning my skin.'\n- Worker attempted de-escalation techniques for 15 minutes; client remained highly agitated and uncooperative.\n- Client threw a glass bottle against the wall, posing a risk to himself and the worker.\n- Worker stepped back and contacted emergency services, requesting the Mobile Crisis Intervention Team (MCIT) due to safety concerns and suspected psychosis.\n- Worker remained on scene observing from a safe distance until police and MCIT arrived.\n- MCIT assessed the client and apprehended him under the Mental Health Act.\n- Worker arranged transport for the client to CAMH emergency department in the police cruiser.\n- Worker provided the responding officers with the client's known medical history and psychiatric diagnoses.\n\n[RISK:HIGH]",
      "Worker met with client following hospital discharge in a public park near the hospital on [Date] at 2:00 PM.\n- Hospital records provided by the client indicate he was held for 72 hours, stabilized on medication, and discharged with a 7-day prescription.\n- Client appeared calm but visibly fatigued and lethargic.\n- Client stated he lost his shelter bed during his hospitalization due to the agency's 48-hour absence policy.\n- Client stated he is currently sleeping rough near City Hall and has no immediate housing options.\n- Worker contacted three local men's shelters; all reported being at full capacity for the night.\n- Worker provided the client with agency emergency supplies, including a thermal blanket, a hygiene kit, and $15 in food vouchers.\n- Worker updated the client's status on the centralized housing registry, changing his profile to 'unsheltered street involved' and adding him to the priority housing waitlist.\n- Worker scheduled a follow-up appointment for the next morning to continue searching for a shelter bed.\n\n[RISK:HIGH]",
      "Worker conducted street outreach contact with client near City Hall on [Date] at 8:30 AM.\n- Worker located the client sleeping on a bench.\n- Client stated he had not slept well and was feeling paranoid.\n- Worker observed the client's medication blister pack; three days of medication had not been taken.\n- Client stated he is taking his medication inconsistently because they make him feel 'slow' and 'vulnerable on the street.'\n- Worker engaged in motivational interviewing to explore the client's ambivalence regarding medication.\n- Worker reminded the client to connect with his Assertive Community Treatment (ACT) team regarding adjusting his dosage.\n- Worker assisted the client in making a phone call to the ACT team psychiatrist; left a voicemail requesting an urgent medication review.\n- Worker accompanied the client to a local drop-in center for breakfast and to use the shower facilities.\n\n[RISK:HIGH]"
    ]
  },
  {
    name: "Nora Blake",
    phone: "+1 (416) 555-0545",
    tags: ["DOMESTIC_VIOLENCE", "HOUSING", "LEGAL"],
    risk_level: "HIGH",
    notes: [
      "Worker conducted emergency intake at women's shelter on [Date] at 2:00 AM.\n- Client arrived at the shelter via police escort with her 4-year-old son.\n- Client stated she fled her home following a violent physical altercation with her common-law partner.\n- Client reported her partner became enraged during an argument about finances, threw a plate at the wall, and grabbed her upper arms forcefully.\n- Worker observed distinct, finger-shaped bruising developing on both of the client's upper arms.\n- Client exhibited visible shaking, hyperventilation, and difficulty focusing on the intake forms.\n- Her child appeared withdrawn and was clinging tightly to the client's leg.\n- Worker provided immediate crisis counseling and reassurance of physical safety within the secure facility.\n- Worker completed the mandatory domestic violence risk assessment tool; score indicated 'Extreme Risk' due to the partner's access to weapons (hunting rifles) and recent escalation in violent behavior.\n- Client refused medical attention for her bruises.\n- Worker assigned the client and her son to a private emergency intake room.\n\n[RISK:HIGH]",
      "Worker conducted comprehensive safety planning session with client at the shelter on [Date] at 10:00 AM.\n- Client appeared more rested but stated she had slept less than three hours.\n- Worker assisted the client in turning off location tracking services on her current mobile phone.\n- Worker provided the client with a new, agency-funded prepaid mobile phone for secure communication.\n- Worker assisted the client in changing passwords and setting up two-factor authentication on her email and banking accounts.\n- Worker discussed legal options with the client, specifically peace bonds and emergency restraining orders.\n- Worker explained the process of applying for exclusive possession of the matrimonial home.\n- Client stated she is currently too overwhelmed and fearful of retaliation to pursue legal action or contact the police to press criminal charges.\n- Worker validated the client's fears and documented her decision not to pursue legal action at this time.\n- Worker and client established a code word ('Yellowknife') for the client to use if she encounters her partner and feels in immediate danger.\n\n[RISK:HIGH]",
      "Worker met with client in the shelter's family room to arrange childcare logistics on [Date] at 1:00 PM.\n- Client stated she needs to maintain her employment (part-time data entry) but cannot leave her son unattended, and her previous childcare arrangement was managed by her abusive partner.\n- Worker assisted the client in completing the expedited application for subsidized municipal daycare, utilizing the domestic abuse priority exemption.\n- Worker contacted three local daycares with available spots; secured a provisional placement starting next Monday pending subsidy approval.\n- Client stated she is experiencing severe anxiety, intrusive memories of the assault, and nightmares.\n- Worker referred the client to the shelter's in-house trauma counselor and scheduled an initial assessment session for Wednesday.\n- Worker observed the client's son engaging positively with the shelter's child life specialist during the meeting.\n\n[RISK:MED]",
      "Worker and municipal housing staff met with client at the housing office on [Date] at 9:00 AM.\n- Worker accompanied the client to provide emotional support and advocacy.\n- Worker and client began the formal application for a Special Priority Program (SPP) housing unit, which prioritizes survivors of domestic violence.\n- Worker reviewed the required documentation with the housing coordinator.\n- Housing coordinator stated the application requires formal documentation verifying the abuse, such as a police report or a letter from a physician or shelter worker.\n- Worker drafted a formal support letter detailing the client's intake circumstances, observed injuries, and the results of the risk assessment tool.\n- Client signed the consent forms allowing the worker to submit the letter directly to the housing registry.\n- Worker submitted all required paperwork and obtained a confirmation receipt.\n\n[RISK:MED]",
      "Worker met with client regarding acute safety concerns in the shelter office on [Date] at 4:00 PM.\n- Client arrived at the office visibly distressed and crying.\n- Client stated she received a highly threatening text message ('You can't hide from me forever. I know you took the boy.') from an unknown, unregistered phone number.\n- Client stated she strongly suspects the sender is her ex-partner based on the phrasing.\n- Worker reviewed the text message and took a photograph of the screen for record-keeping purposes.\n- Worker advised the client not to respond to the message.\n- Worker reviewed the previously established safety plan, reinforcing the instruction not to travel alone outside the shelter.\n- Worker and client contacted the local police division via the non-emergency line to file a formal report regarding the threatening communication.\n- Two officers arrived at the shelter at 5:30 PM; worker sat with the client while she provided a statement to the police.\n- Police documented the incident and warned the client that her ex-partner may be actively searching for her.\n\n[RISK:HIGH]"
    ]
  },
  {
    name: "Samuel Tucker",
    phone: "+1 (416) 555-0656",
    tags: ["SENIOR", "MEDICAL"],
    risk_level: "MED",
    notes: [
      "Worker received standard referral from client's primary care physician and completed chart review on [Date].\n- Medical records indicate the client is an 82-year-old widower.\n- Significant medical history includes failing eyesight (macular degeneration), early-stage Parkinson's disease resulting in mild tremors, and hypertension.\n- Client resides alone in a two-story, privately owned detached house.\n- The physician's report states the client is losing weight unexpectedly and appears to be struggling to maintain his property and personal hygiene.\n- Physician noted the client repeatedly forgets or misses medical appointments.\n- Worker telephoned the client to introduce services; client was initially resistant, stating, 'I don't need charity,' but eventually agreed to a brief introductory home visit next Tuesday.\n\n[RISK:MED]",
      "Worker conducted initial home visit at client's residence on [Date] for 45 minutes.\n- Worker observed the exterior of the house showed signs of neglect (overgrown grass, peeling paint).\n- Inside, worker observed the house is cluttered with stacks of newspapers and mail, but pathways are clear and functionally safe.\n- Worker observed expired food in the refrigerator and a lack of fresh provisions.\n- Client exhibited a noticeable hand tremor while attempting to pour a glass of water.\n- Client stated a strong, explicit desire to maintain his independence and remain in his own home.\n- Client stated he is having difficulty managing the laundry located in the basement due to the stairs.\n- Worker discussed municipal support services designed to help seniors age in place.\n- Client reluctantly agreed to a trial period of assistance.\n- Worker arranged for a weekly Personal Support Worker (PSW) through the Home and Community Care program for bathing assistance and light housekeeping (laundry and meal prep).\n\n[RISK:MED]",
      "Worker conducted follow-up phone call with client on [Date] at 10:00 AM.\n- Worker inquired about the first visit from the assigned PSW.\n- Client stated he sent the PSW away after 15 minutes because she was 'bossing him around' and 'trying to throw out important papers.'\n- Worker validated the client's frustration while explaining the PSW's mandate to ensure a sanitary environment.\n- Worker committed to contacting the care agency to request an alternative PSW with experience handling resistant clients, specifically requesting a male worker if possible.\n- Worker noted a stack of unpaid utility bills during the previous visit and raised the topic of financial management.\n- Worker discussed the benefits of setting up automated bill payments with the client's bank to prevent service interruptions.\n- Client agreed to allow the worker to assist him with banking setup during the next in-person visit.\n\n[RISK:LOW]",
      "Worker scheduled specialized transportation services for client via phone on [Date].\n- Client called the worker stating he missed an important follow-up appointment with his ophthalmologist.\n- Client stated he missed the appointment because he no longer feels safe driving and could not afford a taxi.\n- Worker completed the medical registration forms for Wheel-Trans (accessible municipal transit) on the client's behalf.\n- Worker faxed the required physician authorization form to the client's doctor for signature.\n- Worker contacted the ophthalmologist's office and rebooked the medical appointment for the third week of the following month.\n- Worker explained the Wheel-Trans booking process to the client and mailed him an information package with the booking phone number in large print.\n\n[RISK:MED]",
      "Worker conducted bi-weekly phone check-in with client on [Date].\n- Client stated the new PSW (David) is a 'much better fit' and respects his boundaries.\n- Client confirmed the PSW assisted with doing two loads of laundry and preparing three meals for the week.\n- Client stated he successfully used Wheel-Trans for grocery shopping the previous day.\n- Worker raised the issue of exterior property maintenance, noting municipal by-law infractions could occur due to the overgrown lawn.\n- Client agreed to allow a local volunteer youth group (from a partner agency) to perform yard work the following weekend.\n- Worker contacted the youth group coordinator to schedule the yard cleanup.\n\n[RISK:LOW]"
    ]
  },
  {
    name: "Kim Jin",
    phone: "+1 (416) 555-0767",
    tags: ["EMPLOYMENT", "FINANCIAL", "HOUSING"],
    risk_level: "MED",
    notes: [
      "Worker met with client for emergency intake at community drop-in center on [Date] at 1:00 PM.\n- Client requested an urgent referral to a local food bank, stating she had not eaten a full meal in two days.\n- Client presented a notice of layoff from her previous employer (administrative assistance) dated 3 months ago.\n- Client provided bank statements showing her severance pay and savings have been completely exhausted; current account balance is $14.50.\n- Client presented an N4 eviction notice (Notice to End a Tenancy Early for Non-payment of Rent) issued by her landlord three days prior.\n- Client stated she is two months behind on her rent ($1400/month).\n- Client exhibited signs of extreme stress, crying intermittently during the intake.\n- Worker provided the client with three emergency food hampers from the center's pantry.\n- Worker initiated an emergency application for the municipal Rent Bank program to cover the rental arrears.\n\n[RISK:HIGH]",
      "Worker mediated with client's landlord via phone conference on [Date] at 10:30 AM.\n- Worker, client, and landlord participated in the call.\n- Landlord expressed frustration over the unpaid rent and stated intent to file with the Landlord and Tenant Board (LTB) by the end of the week.\n- Worker explained that an application for the Rent Bank had been submitted on the client's behalf.\n- Worker negotiated a formal, written payment plan with the landlord, proposing that the Rent Bank will cover the arrears and the client will pay a portion of the upcoming rent utilizing pending Employment Insurance (EI) benefits.\n- Landlord verbally agreed to suspend the LTB filing for 14 days to allow the Rent Bank application to process.\n- Worker assisted the client in calling Service Canada to expedite her pending EI claim, providing the eviction notice as proof of dire need.\n- Worker requested the landlord send the ledger of arrears via email for the Rent Bank file.\n\n[RISK:MED]",
      "Worker met with client regarding financial and employment status at the agency office on [Date] at 2:00 PM.\n- Worker provided the client with the approval letter from the Rent Bank program; a direct payment of $2800 was issued to the landlord, covering the back rent.\n- Client expressed significant relief and stated she feels she can focus on job searching again.\n- Worker spent 60 minutes reviewing the client's resume and cover letter templates.\n- Worker noted the resume had employment gaps and outdated formatting.\n- Worker assisted the client in optimizing her resume for Applicant Tracking Systems (ATS) used by administrative employers.\n- Worker and client successfully submitted five applications for receptionist and data entry roles during the meeting.\n\n[RISK:LOW]",
      "Worker conducted follow-up meeting with client on [Date] at 3:00 PM.\n- Client stated she is receiving her EI benefits regularly, stabilizing her immediate financial situation.\n- Client stated she has applied to over 40 positions but has not received any interview requests.\n- Client exhibited a flat affect and stated she is feeling discouraged and 'useless.'\n- Worker validated the difficulty of the current job market.\n- Worker provided the client with an information brochure on a government-funded, short-term bookkeeping retraining program designed to upgrade administrative skills.\n- Client expressed interest in the bookkeeping program.\n- Worker scheduled an appointment for the client to meet with a vocational counselor the following week to assess eligibility for the retraining program.\n\n[RISK:LOW]"
    ]
  },
  {
    name: "Tyler Dunn",
    phone: "+1 (416) 555-0878",
    tags: ["YOUTH", "SUBSTANCE_USE"],
    risk_level: "HIGH",
    notes: [
      "Worker conducted initial street outreach meeting with client (age 18) on [Date] at 9:00 PM in an alleyway.\n- Client recently aged out of the foster care system two months prior.\n- Client presented with poor hygiene and stated he has been couch-surfing or sleeping outside since leaving care.\n- Worker observed client actively drinking from a bottle of cheap liquor during the interaction.\n- Client exhibited rapid speech and stated he experiences severe, constant anxiety.\n- Client stated he consumes alcohol daily as a means to 'self-medicate' and stop his panic attacks.\n- Client refused a spot at a youth shelter, stating 'they steal your stuff there.'\n- Worker provided client with harm reduction supplies, thick socks, and bottled water.\n- Worker scheduled a daytime meeting at a local youth hub with the promise of a hot meal.\n\n[RISK:HIGH]",
      "Worker met with client at the designated youth drop-in hub on [Date] at 1:00 PM.\n- Client arrived on time and consumed a hot meal provided by the hub.\n- Client exhibited initial defensiveness when asked about housing options, crossing his arms and avoiding eye contact.\n- Worker utilized a trauma-informed approach, focusing on the client's immediate comfort rather than long-term planning.\n- Client verbally agreed to allow the worker to look into housing assistance programs, explicitly stating he wants a bachelor apartment, not a shared unit.\n- Worker created a profile for the client on the centralized youth housing registry.\n- Worker acquired signed consent forms from the client to request his medical records regarding his anxiety diagnosis.\n- Worker provided client with a list of safe sleeping locations for the upcoming weekend.\n\n[RISK:MED]",
      "Worker investigated a critical incident involving client at the youth hub via phone on [Date] at 10:00 AM.\n- Hub staff reported client was involved in a physical altercation with another youth the previous evening.\n- Staff stated client threw a chair across the recreation room during a minor disagreement over a pool game.\n- Staff stated client appeared intoxicated during the altercation.\n- Client is temporarily barred from entering the hub for 7 days per agency violence policies.\n- Worker contacted the client's former foster worker to obtain collateral information regarding triggers for aggression.\n- Former worker stated the client has a history of explosive outbursts when feeling 'cornered' or embarrassed.\n- Worker attempted to call the client four times; phone went straight to voicemail.\n\n[RISK:HIGH]",
      "Worker located client at a local community skate park during outreach rounds on [Date] at 4:30 PM.\n- Client was sitting alone and appeared remorseful.\n- Worker discussed the incident at the youth hub; client admitted he was intoxicated and 'overreacted' because the other youth insulated his jacket.\n- Worker discussed anger management strategies and the direct consequences of the hub ban (loss of meals, loss of shower access).\n- Worker emphasized the importance of accountability in maintaining access to services.\n- Client verbally agreed to draft a formal apology letter to the hub staff and the other youth involved.\n- Worker provided the client with paper and pen; client spent 20 minutes drafting the letter on-site.\n- Worker reviewed the letter with the client and agreed to deliver it to the hub supervisor.\n\n[RISK:MED]",
      "Worker coordinated a mediation meeting with youth hub staff regarding client on [Date] at 11:00 AM.\n- Worker presented the client's apology letter to the hub supervisor and the staff member present during the altercation.\n- Supervisor accepted the apology letter and agreed to lift the entry ban on a probationary basis, dependent on the client's behavior.\n- Worker and supervisor established a condition that the client must attend at least two sessions with the hub's on-site mental health counselor to address his anxiety and trigger responses.\n- Worker met with the client and communicated the probationary terms.\n- Client verbally agreed to the terms and immediately scheduled his first counseling session for the following afternoon.\n\n[RISK:LOW]",
      "Worker conducted routine check-in with client at a coffee shop on [Date] at 2:00 PM.\n- Client presented appearing clean and appropriately dressed.\n- Client stated he attended his first counseling session the previous day and felt the counselor 'wasn't terrible.'\n- Client stated an older friend he met at the skate park offered him a room to rent in a shared house for $600/month.\n- Client stated a viewing of the room is scheduled for Friday.\n- Worker discussed the responsibilities of tenancy and shared living arrangements.\n- Client stated he has no savings for the required first and last month's rent.\n- Worker committed to researching municipal rental setup assistance funds for youth transitioning out of care and began compiling the necessary application paperwork.\n\n[RISK:LOW]"
    ]
  },
  {
    name: "Maria Gonzalez",
    phone: "+1 (416) 555-0989",
    tags: ["MEDICAL", "FAMILY_SUPPORT"],
    risk_level: "LOW",
    notes: [
      "Worker received referral from the local hospital's neurology department for client on [Date].\n- Conducted initial phone consultation with the client.\n- Medical records indicate the client's husband (age 65) suffered a severe ischemic stroke two months ago, resulting in left-side paralysis and expressive aphasia.\n- Husband was recently discharged home, requiring full-time assistance with Activities of Daily Living (ADLs).\n- Client stated she had to quit her job to provide 24/7 care for her husband.\n- Client stated she feels completely overwhelmed, sleep-deprived, and unsure how to navigate the home healthcare system.\n- Client stated, 'I love him, but I can't lift him by myself anymore.'\n- Worker scheduled an urgent in-home accessibility evaluation.\n\n[RISK:MED]",
      "Worker conducted comprehensive home accessibility evaluation at client's residence on [Date] for 90 minutes.\n- Worker observed the client struggling to transfer her husband from his wheelchair to the living room recliner.\n- Worker assessed the physical environment: four steep stairs leading to the front door, a narrow hallway, and a standard bathtub lacking safety features.\n- Worker recommended immediate installation of a temporary aluminum ramp for the front stairs to allow wheelchair egress.\n- Worker recommended installation of grab bars and a transfer bench in the bathroom.\n- Worker assisted the client in completing applications for the provincial Home and Vehicle Modification Program (HVMP) grants.\n- Worker provided the client with a catalogue of required medical equipment and contacted a vendor to arrange quotes for the grant application.\n\n[RISK:LOW]",
      "Worker conducted follow-up meeting with client regarding caregiver burnout on [Date] at 1:00 PM.\n- Worker observed the client appearing exhausted, with dark circles under her eyes.\n- Client stated she is experiencing back pain from lifting her husband and has not left the house for non-medical reasons in three weeks.\n- Worker discussed the critical importance of respite care to prevent caregiver injury and burnout.\n- Worker contacted the local Community Care Access Centre (CCAC) and successfully requested an allocation of 8 hours of weekly in-home PSW respite care for the husband.\n- Worker provided the client with the schedule and contact information for a local, weekly caregiver support group hosted at the community center.\n- Client agreed to utilize the PSW hours to attend the support group and rest.\n\n[RISK:LOW]"
    ]
  },
  {
    name: "Henry Cobb",
    phone: null,
    tags: ["MENTAL_HEALTH", "HOUSING", "MEDICAL"],
    risk_level: "HIGH",
    notes: [
      "Worker conducted targeted street outreach at the Don Valley ravine encampment on [Date] at 7:00 AM.\n- Worker located the client residing in a makeshift tent structure deep within the ravine.\n- Agency records indicate the client has a long-standing diagnosis of severe, untreated schizophrenia and has been unsheltered for approximately 5 years.\n- Worker approached cautiously; client was observed organizing a large collection of discarded electronics outside his tent.\n- Client appeared highly disorganized in his thought processes, frequently interrupting the worker to discuss 'the electromagnetic pulse grids.'\n- Worker observed a significant, untreated laceration on the client's lower right leg, which appeared swollen and discolored.\n- Worker attempted to discuss basic medical care; client refused, stating hospitals are run by 'government trackers.'\n- Worker left bottled water, protein bars, and a weather-proof tarp, promising to return the following week.\n\n[RISK:MED]",
      "Worker returned to encampment accompanied by a street-involved mobile health nurse on [Date] at 9:00 AM.\n- Worker and nurse spent 30 minutes building rapport with the client before mentioning his leg.\n- Client reluctantly allowed the nurse a brief, visual inspection of the wound on his leg from a distance of two feet.\n- Nurse noted severe localized infection with signs of developing cellulitis.\n- Nurse offered oral antibiotics; client explicitly and aggressively refused the medication, stating it was 'poison.'\n- Nurse and worker determined the situation did not yet meet the criteria for involuntary apprehension under the Mental Health Act, as the client was not in immediate, acute distress.\n- Nurse provided the client with a sterile wound care kit (saline, clean bandages, antibiotic ointment) and instructed him on how to apply them himself.\n- Worker documented the refusal of treatment and prioritized the client on the high-risk outreach monitoring list for daily checks.\n\n[RISK:HIGH]",
      "Worker met with client regarding impending encampment clearing on [Date] at 10:30 AM.\n- Worker visited the encampment specifically to inform the client that municipal by-law enforcement intends to clear the ravine area within 48 hours.\n- Worker provided the client with formal city documentation regarding the clearing.\n- Worker proposed immediate relocation to a specialized shelter hotel that accommodates individuals with severe mental health challenges and allows possession of some collected items.\n- Client expressed extreme suspicion of government services, stating the clearing is a tactic to 'confiscate my transmitters.'\n- Client adamantly refused relocation assistance or shelter placement.\n- Worker provided the client with two large heavy-duty duffel bags to help him transport his most important belongings.\n- Worker informed the client of the specific date and time the clearing crew would arrive.\n\n[RISK:HIGH]",
      "Worker located client downtown outside a subway station following the encampment clearing on [Date] at 2:00 PM.\n- Worker observed the client exhibiting severe emotional distress, pacing erratically and shouting at pedestrians.\n- Client was carrying only one of the provided duffel bags.\n- Client stated he lost his tent, his winter sleeping bag, and the majority of his electronics during the morning clearing operation.\n- Client appeared cold and disoriented.\n- Worker purchased the client a hot coffee and a sandwich, sitting with him on a bench for 45 minutes to de-escalate the situation.\n- Worker convinced the client that sleeping on the street without a sleeping bag would be dangerous due to impending freezing temperatures.\n- With the client's highly hesitant agreement, worker transported him in the agency vehicle to a specialized low-barrier, harm-reduction shelter.\n- Worker facilitated the intake process and ensured the client was assigned a bed away from busy communal areas.\n\n[RISK:HIGH]",
      "Worker contacted the low-barrier shelter regarding client status on [Date] at 9:00 AM.\n- Shelter staff stated the client spent the night in his assigned bed but departed the facility abruptly at 6:00 AM.\n- Staff reported the client appeared agitated prior to departure, complaining about 'the hum of the fluorescent lights.'\n- Staff noted the client left behind his duffel bag containing his remaining belongings.\n- Worker collected the client's bag from the shelter and stored it securely at the agency office.\n- Worker added the client to the afternoon street outreach route, targeting his known secondary locations (subway grates, specific underpasses).\n- Worker circulated a physical description and the client's latest known whereabouts to the broader municipal outreach network.\n\n[RISK:HIGH]"
    ]
  },
  {
    name: "Chloe & Liam Peterson",
    phone: "+1 (416) 555-1010",
    tags: ["FAMILY_SUPPORT", "LEGAL"],
    risk_level: "MED",
    notes: [
      "Worker received formal referral from Children’s Aid Society (CAS) and reviewed the family file on [Date].\n- CAS report indicated involvement was initiated due to a call from the children's elementary school principal reporting suspected neglect.\n- Report detailed the parents' substantial history of opioid use and prior CAS interventions.\n- The stated goal of the current CAS involvement is family preservation, providing the parents comply with a strict service plan.\n- Worker contacted the assigned CAS investigating social worker to coordinate intervention strategies.\n- Worker scheduled a mandatory joint initial meeting with the parents at their residence for the following Monday.\n\n[RISK:MED]",
      "Worker conducted initial joint meeting with clients (parents Chloe and Liam) at their apartment on [Date] for 60 minutes.\n- Worker clearly explained their role as an independent family support worker distinct from the CAS investigator.\n- Both clients presented as well-groomed and lucid.\n- Worker inquired directly about current substance use; both clients vehemently verbally denied any current use of opioids or illicit substances, though acknowledged past struggles.\n- Worker reviewed the conditions of the CAS service plan, which includes random, mandatory urine drug screening.\n- Clients expressed anger regarding the drug screening requirement, viewing it as invasive.\n- Worker spent 20 minutes explaining the legal implications of non-compliance with CAS directives regarding child custody.\n- Clients reluctantly signed the consent forms agreeing to the screening protocol and the overall service plan.\n\n[RISK:MED]",
      "Worker conducted unannounced spot-check home visit on [Date] at 11:30 AM.\n- Client Chloe answered the door; appeared slightly surprised but permitted entry.\n- Worker conducted a comprehensive walkthrough of the two-bedroom apartment.\n- Worker observed the residence was reasonably clean and free of obvious physical hazards (e.g., exposed wires, drug paraphernalia).\n- Worker inspected the kitchen; observed the refrigerator and pantry were fully stocked with age-appropriate food (fresh milk, fruit, cereal).\n- Worker observed the two children (ages 2 and 5) watching television in the living room.\n- Both children appeared clean, appropriately dressed for the weather, and showed no visible signs of physical neglect or distress.\n- Worker documented the positive observations to report back to the CAS team.\n\n[RISK:LOW]",
      "Worker attended emergency strategy meeting with CAS representatives and the clients at the CAS office on [Date] at 1:00 PM.\n- CAS investigator presented the results of a mandatory drug screen conducted three days prior.\n- Client Liam tested positive for high levels of fentanyl and non-prescribed methadone.\n- CAS representative stated that due to the severe safety risk, they intend to pursue an immediate child apprehension order unless a stringent safety plan is enacted immediately.\n- Client Chloe appeared shocked and began crying; client Liam admitted to a relapse that began two weeks ago.\n- Worker intervened to mediate the severe conflict and prevent total family breakdown.\n- Worker, CAS, and clients spent two hours formulating a rigorous crisis safety plan.\n- Plan explicitly requires Liam to vacate the family home immediately and enter supervised detoxification.\n\n[RISK:HIGH]",
      "Worker monitored safety plan implementation at the client's residence on [Date] at 9:00 AM.\n- Worker arrived at the apartment to verify compliance with the emergency safety plan.\n- Worker confirmed client Liam had moved out of the primary residence the previous evening and was currently staying with his brother.\n- Client Chloe provided documentation showing Liam is scheduled to enter a 30-day residential detox program on Thursday.\n- Client Chloe has assumed sole, full-time caregiving duties for the children.\n- Client Chloe reported feeling overwhelmed but committed to keeping the children in her care.\n- Worker and client established a schedule for daily check-in phone calls and twice-weekly in-person visits to monitor the children's welfare and Chloe's stress levels.\n- Worker provided Chloe with an emergency grocery card as her access to joint funds was temporarily restricted.\n\n[RISK:MED]"
    ]
  },
  {
    name: "Robert Lin",
    phone: "+1 (416) 555-1212",
    tags: ["SENIOR", "HOUSING", "MENTAL_HEALTH"],
    risk_level: "HIGH",
    notes: [
      "Worker investigated property standards complaint at the client's detached home on [Date] at 10:00 AM.\n- Complaint was filed by neighbors regarding severe exterior neglect and pest concerns.\n- Worker approached the residence and observed windows completely obscured by stacked belongings.\n- Client answered the door but only opened it 4 inches.\n- Through the crack, worker observed severe hoarding conditions; newspapers, boxes, and clothing were stacked higher than the doorframe.\n- Worker noted these conditions pose immediate, high-level fire and structural collapse risks.\n- Client exhibited extreme hostility toward the worker's presence, shouting, 'This is private property, I'm calling the police!'\n- Worker attempted to calmly explain the municipal complaint process, but the client slammed the door.\n- Worker documented the exterior conditions, took photographs of the yard, and placed a formal alert on the municipal address regarding fire hazards.\n\n[RISK:HIGH]",
      "Worker accompanied the municipal fire inspector on a mandatory property inspection on [Date] at 9:00 AM.\n- Client permitted entry to the front entryway solely under threat of a legal entry warrant by the fire inspector.\n- Worker and inspector were unable to proceed past the front hallway due to debris.\n- Worker observed stacked items reaching the 8-foot ceiling in the living and dining rooms.\n- The kitchen was inaccessible, and the inspector noted the absence of working smoke detectors in the visible areas.\n- Fire inspector formally issued a 'Notice of Violation and Order to Comply,' mandating the client clear safety compliance pathways within 30 days.\n- Inspector informed the client that failure to comply would result in municipal crews forcibly clearing the property at the client's expense.\n- Client appeared highly anxious, pacing the small clear area and exhibiting shortness of breath.\n- Worker provided the client with the agency contact card, urging him to call for assistance with the clearing process.\n\n[RISK:HIGH]",
      "Worker met with client's estranged daughter at a local coffee shop on [Date] at 1:00 PM.\n- Worker tracked down the daughter's contact information via a previous hospital record.\n- Daughter verbally confirmed the client has a 30-year history of severe Obsessive-Compulsive Disorder (OCD) manifesting as hoarding behavior, which escalated significantly after his wife's passing.\n- Daughter stated she has attempted to clean the house multiple times in the past, resulting in the client becoming physically aggressive and cutting off communication.\n- Daughter stated her willingness to assist financially with professional cleaning services, but noted the client steadfastly refuses her help or presence in the home.\n- Worker and daughter discussed the intricacies of trauma-informed decluttering versus standard junk removal.\n- Worker acquired signed third-party consent forms from the daughter to coordinate funding applications for specialized intervention services.\n\n[RISK:MED]",
      "Worker conducted meeting with client on the front porch of his residence on [Date] at 2:00 PM.\n- Client appeared less hostile than previous encounters, presenting the Order to Comply document to the worker.\n- Client stated he felt overwhelmed and paralyzed by the order, stating he didn't know where to start without 'throwing away my memories.'\n- Worker utilized motivational interviewing techniques to discuss safety goals rather than focusing on 'cleaning.'\n- Client verbally agreed to a highly specific, limited goal: allowing assistance to clear a single 36-inch pathway from the front door to the kitchen to satisfy the immediate fire code violation.\n- Worker explained the process of utilizing a specialized, trauma-informed hoarding team that works with the client's consent on every item discarded.\n- Worker submitted an urgent funding request to the municipal extreme clean fund to cover the cost of the specialized service.\n- Worker scheduled the initial assessment with the cleaning team for the following Monday.\n\n[RISK:MED]"
    ]
  },
  {
    name: "Zainab Al-Fayed",
    phone: "+1 (416) 555-1313",
    tags: ["DOMESTIC_VIOLENCE", "LEGAL", "IMMIGRATION"],
    risk_level: "HIGH",
    notes: [
      "Worker received formal referral from the community health center and conducted phone intake on [Date] for 45 minutes.\n- Client utilized a secure phone at the clinic to make the call.\n- Client stated she arrived in Canada two years ago under spousal sponsorship and is experiencing escalating financial and emotional abuse from her husband.\n- Client reported her husband controls all household finances, confiscates her wages from working at a bakery, and frequently threatens her with deportation if she disobeys him.\n- Client stated her husband monitors her phone communications and restricts her movements, only allowing her to travel to work and the grocery store.\n- Worker identified the situation as severe coercive control.\n- Client stated her immigration status (permanent residency) is currently conditional upon remaining with her sponsor (husband) for the mandated duration.\n- Worker scheduled a secure, in-person meeting at a discrete location (local library meeting room) for the following week.\n\n[RISK:HIGH]",
      "Worker consulted with an immigration lawyer at a community legal clinic regarding the client's specific case on [Date] for 60 minutes.\n- Worker provided the lawyer with an anonymized overview of the client's domestic abuse situation and sponsorship status.\n- Worker and lawyer discussed the legal process for the client to apply for an exemption to the conditional permanent residence requirement due to abuse.\n- Lawyer confirmed the client may be eligible to apply for status independently under Humanitarian and Compassionate (H&C) considerations.\n- Lawyer noted the application requires substantial evidence of the abuse, such as affidavits from community workers, medical records, or police reports.\n- Worker requested the lawyer open a file for the client and arranged for legal aid funding to cover the consultation costs.\n- Worker drafted a list of necessary evidentiary documents needed to support the impending immigration application.\n\n[RISK:MED]",
      "Worker conducted secure meeting with client at the local library meeting room on [Date] at 10:00 AM.\n- Worker presented the information gathered from the immigration lawyer, explaining her rights and options regarding maintaining her residency status independent of her abuser.\n- Client appeared relieved to hear she would not automatically be deported if she left.\n- However, client stated she is not prepared to physically leave the shared residence at this time due to intense fear of losing custody of her three children and retaliation from her husband's family.\n- Worker respected the client's timeline and shifted focus to harm reduction within the home.\n- Worker collaborated with the client to develop a detailed, covert safety plan while she remains in the residence (identifying safe rooms, keeping a 'go-bag' hidden at her workplace).\n- Worker assisted the client in establishing a private, online-only bank account through a separate institution, ensuring no physical mail would be sent to the home.\n- Client agreed to attempt to secretly deposit a small portion of her tips into the new account to build an emergency exit fund.\n\n[RISK:HIGH]"
    ]
  },
  {
    name: "Dominic Foster",
    phone: "+1 (416) 555-1414",
    tags: ["VETERAN", "MENTAL_HEALTH", "SUBSTANCE_USE"],
    risk_level: "MED",
    notes: [
      "Worker received detailed referral from the regional Veterans Affairs (VA) transition office on [Date].\n- Reviewed 40-page military medical file and transition summary.\n- Client served two combat tours in Afghanistan as an infantryman; medically discharged four years ago.\n- Official clinical diagnosis includes severe, chronic Post-Traumatic Stress Disorder (PTSD) and moderate hearing loss.\n- Referral indicates the client has become increasingly socially isolated over the past year, rarely leaving his apartment.\n- VA counselor noted the client self-reports frequently consuming large quantities of alcohol to cope with intrusive memories and hypervigilance.\n- Worker verified the client is currently receiving a partial disability pension but may be eligible for a higher assessment.\n- Worker initiated contact via postal mail, as the referral noted the client does not typically answer phone calls from unknown numbers.\n\n[RISK:MED]",
      "Worker conducted initial home visit at client's apartment on [Date] at 1:00 PM.\n- Client permitted entry; worker observed the apartment to be dark, with blackout curtains drawn over all windows.\n- Client presented as guarded, maintaining a tactical stance and sitting facing the door during the 45-minute interaction.\n- Client stated he experiences severe sleep disturbances, averaging two hours of sleep per night due to complex nightmares.\n- Worker observed empty liquor bottles in the kitchen recycling bin but the client did not appear currently intoxicated.\n- Worker discussed the limitations of his current VA-provided general counseling.\n- Worker provided the client with a targeted referral to a specialized clinical psychologist who focuses exclusively on military trauma and EMDR (Eye Movement Desensitization and Reprocessing) therapy.\n- Worker assisted the client in calling the clinic to schedule an intake assessment.\n\n[RISK:MED]",
      "Worker met with client regarding financial and social benefits at the agency office on [Date] at 10:00 AM.\n- Client arrived early; appearing less guarded but still highly observant of his surroundings.\n- Worker and client spent 90 minutes completing the intricate VA documentation required to request an reassessment for upgraded disability benefits based on the worsening severity of his PTSD symptoms.\n- Worker attached supporting documentation from the newly assigned trauma therapist.\n- Worker discussed the client's profound social isolation and the negative impact it has on his recovery.\n- Worker introduced a brochure for a local non-profit organization that runs structured outdoor recreation programs (fishing, hiking) specifically designed for combat veterans.\n- Worker emphasized the peer-support aspect of the program with individuals possessing shared experiences.\n- Client expressed mild interest and agreed to allow the worker to forward his contact information to the program coordinator.\n\n[RISK:LOW]",
      "Worker conducted follow-up phone call with client on [Date] at 4:00 PM.\n- Client answered the phone promptly and sounded more energetic than in previous interactions.\n- Client stated he attended the veteran recreation program's weekend fishing trip to a northern lake.\n- Client reported he enjoyed the experience and found it surprisingly easy to converse with the other veterans present.\n- Client noted he felt relaxed being outdoors away from the noise of the city.\n- Crucially, client stated he did not consume any alcohol during the three-day trip and has maintained his sobriety for a full week total.\n- Worker praised the client's significant progress and discussed strategies to maintain momentum.\n- Client confirmed he has scheduled a follow-up trip with the group for the next month and is continuing his EMDR therapy.\n\n[RISK:LOW]"
    ]
  },
  {
    name: "Patricia O'Connor",
    phone: "+1 (416) 555-1515",
    tags: ["MEDICAL", "MENTAL_HEALTH"],
    risk_level: "MED",
    notes: [
      "Worker received complex case referral from the local hospital Emergency Department (ED) triage coordinator on [Date].\n- Extensive review of the client's hospital records revealed a striking pattern: the 78-year-old client visited the ED 12 distinct times in the preceding 30 days.\n- Hospital medical records indicate the client consistently presents complaining of vague chest pains, shortness of breath, or undefined 'dizziness.'\n- Each visit involved comprehensive cardiac and respiratory testing; all resulting in negative findings for acute physical emergencies.\n- Triage notes indicate a strong suspicion that the client's presentations are manifestations of severe anxiety or panic attacks rather than cardiac events.\n- The explicit goal of the social work referral is to implement community-level interventions to reduce the client's severe reliance on emergency medical services for non-emergency issues.\n- Worker structured a plan to assess social determinants of health driving the ED visits.\n\n[RISK:MED]",
      "Worker conducted comprehensive 2-hour home visit and psychosocial assessment at client's townhouse on [Date].\n- Worker observed the home to be meticulously clean and well-maintained.\n- Client presented as highly anxious, frequently checking her pulse and blood pressure with an at-home machine during the conversation.\n- Client stated she experiences overwhelming feelings of loneliness and impending doom, particularly in the evenings when she is unaccompanied.\n- Client reported her husband passed away six months ago, and she feels 'unanchored.'\n- Client stated she goes to the hospital because 'the nurses are nice to me and make me feel incredibly safe.'\n- Client revealed her primary care physician of 20 years recently retired, leaving her without a trusted primary care contact and forcing her to utilize walk-in clinics or the ED for minor concerns.\n- Worker identified profound social isolation and bereavement as the primary drivers of the anxiety and frequent ED utilization.\n\n[RISK:MED]",
      "Worker met with client to execute the care coordination plan at a local Family Health Team clinic on [Date] at 9:00 AM.\n- Worker successfully secured a coveted roster spot for the client with a new geriatric-specialized physician at the clinic.\n- Worker accompanied the client to her initial 'meet and greet' appointment to ensure all medical records were smoothly transferred from the hospital and previous doctor.\n- Physician comprehensively reviewed the client's recent negative cardiac workups and prescribed a mild anti-anxiety medication to be used as needed.\n- Following the medical appointment, worker assisted the client via phone in enrolling in a municipal 'Telecheck' program.\n- The program guarantees the client will receive a daily telephone reassurance and check-in call from a trained senior volunteer every evening at 6:00 PM.\n- Client expressed immediate relief at having a dedicated family doctor again and a scheduled daily contact point.\n\n[RISK:LOW]",
      "Worker conducted a one-month status review check-in regarding the client on [Date].\n- Worker accessed the regional hospital database; records conclusively indicate the client has not visited the ED or any urgent care center in the past four weeks.\n- Worker called the client at home; client sounded cheerful and engaged.\n- Client stated the daily 6:00 PM phone calls from the Telecheck volunteer significantly alleviate her evening anxiety spikes, noting she and the volunteer have 'become friends.'\n- Client reported taking her anti-anxiety medication only twice in the last month.\n- Worker identified the need to build sustainable, in-person social connections beyond the daily phone call.\n- Worker discussed the concept of municipal Adult Day Programs, which offer structured social activities, exercise, and meals for seniors.\n- Client expressed nervousness but agreed to attend a trial half-day session if the worker accompanied her for the first hour.\n- Worker committed to researching local programs with transportation options and scheduling a facility tour.\n\n[RISK:LOW]"
    ]
  }
];
